In [36]:
import numpy as np

In [37]:
a=np.array([[1,2,3,4]])
b=np.array([[1,2,3,5],[4,5,6,7]])
print(b.ndim)
print(b.size)
print(b.itemsize)
print(b.size*b.itemsize)
print(a.ndim)
print(a.size)
print(a.itemsize)
print(a.size*a.itemsize)
print(a.shape)
print(b.shape)
print(a.dtype)

2
8
8
64
2
4
8
32
(1, 4)
(2, 4)
int64


In [38]:
a=np.array([1,2,3,4])<<np.array([1,2,3,4])
b=b.reshape(4,2)
b

array([[1, 2],
       [3, 5],
       [4, 5],
       [6, 7]])

In [39]:
b=np.array([(4,16,36,49),(9,25,81,100)])
c=2
g=np.array([1,2,3,4,9])
print(b.sum(axis=0))
print(b.sum(axis=1))
print(b.max())
print(b.min())
print(np.sqrt(b))
print(np.std(b))
print(np.mean(g))
print(np.median(g))
print(np.exp(b))
print(np.log2(c))

[ 13  41 117 149]
[105 215]
100
4
[[ 2.  4.  6.  7.]
 [ 3.  5.  9. 10.]]
32.47306576225903
3.8
3.0
[[5.45981500e+01 8.88611052e+06 4.31123155e+15 1.90734657e+21]
 [8.10308393e+03 7.20048993e+10 1.50609731e+35 2.68811714e+43]]
1.0


In [40]:
e=np.array([(1,2,3,4),(5,6,7,8)])
f=np.array([(1,2,3,4),(5,6,7,8)])
print(e.ndim)
print(np.vstack((e,f)))
print(np.hstack((e,f)))
print(e.ravel())

2
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [55]:
a=np.array([1,2,3,4])
b=np.array([5,9,7,8])
c=np.concatenate((a,b),axis=0)
a=np.expand_dims(a,axis=0)
print(a.shape)
print(a)

print(c)
print(np.sort(c))
d.shape

(1, 4)
[[1 2 3 4]]
[1 2 3 4 5 9 7 8]
[1 2 3 4 5 7 8 9]


(4,)

In [64]:
a = np.array([[1, 2, 7, 4], [5, 6, 7, 8], [1, 10, 11, 12]])
b=a.copy()
print(b)
print(a[a<5])
print(a[a%2==0])
print(a+b)

[[ 1  2  7  4]
 [ 5  6  7  8]
 [ 1 10 11 12]]
[1 2 4 1]
[ 2  4  6  8 10 12]
[[ 2  4 14  8]
 [10 12 14 16]
 [ 2 20 22 24]]


In [73]:
from scipy.special import factorial
print(int(factorial(5)))

120


In [70]:
def factorial_n(n):
  return np.prod(np.arange(1,n+1))
print(factorial_n(5))


120


In [71]:
import math
print(math.factorial(5))

120
