###Single Dimensional Array

In [5]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


###Multi-Dimensional array

In [6]:
b=np.array([(7,8,9,10),(11,12,13,14)])
c=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
print(b)
print(c)

[[ 7  8  9 10]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


###Generative Array

In [8]:
d=np.arange(5)
e=np.linspace(1,5,6)
print(d)
print(e)


[0 1 2 3 4]
[1.  1.8 2.6 3.4 4.2 5. ]


###Array Properties

In [16]:
from genericpath import getsize
a=np.array([7,8,9,10])
b=np.array([(7,8,9,10),(11,12,13,14)])
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.size*a.itemsize)
print(a.size)
print(a.shape)

1
8
int64
32
4
(4,)


In [17]:
b=np.array([(7,8,9,10),(11,12,13,14)])
print(b)
b=b.reshape(4,2)
print(b)

[[ 7  8  9 10]
 [11 12 13 14]]
[[ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


###Array slicing

In [25]:
b=np.array([(7,8,9,10),(11,12,13,14)])
print(b[0,2])
print(b[0:,2])
c=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])		#Multi-Dimensional Array
print(c[1:,2])

9
[ 9 13]
[ 7 11]


###Array Value Operation

In [26]:
b=np.array([(7,8,9,10),(11,12,13,14)])
print(b.min())
print(b.max())
print(b.sum())

7
14
84


In [28]:
b=np.array([(7,8,9,10),(11,12,13,14)])
print(b.sum(axis=0))
print(b.sum(axis=1))
print(np.sqrt(b[0]))
print(np.std(b))
print(np.log(b))
print(np.exp(b))


[18 20 22 24]
[34 50]
[2.64575131 2.82842712 3.         3.16227766]
2.29128784747792
[[1.94591015 2.07944154 2.19722458 2.30258509]
 [2.39789527 2.48490665 2.56494936 2.63905733]]
[[1.09663316e+03 2.98095799e+03 8.10308393e+03 2.20264658e+04]
 [5.98741417e+04 1.62754791e+05 4.42413392e+05 1.20260428e+06]]
